spring:
  application:
    name: data-platform
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000
          order_inserts: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 8
      maximum-pool-size: 8
      transaction-isolation: TRANSACTION_READ_COMMITTED #降低事务隔离级别，提高写入速度
server:
  port: 8081

authentication:
  tokenTimeout: 30
  #不校验权限接口
  permit: /health,/static/**,/auth/resetRootPassword

user:
  root: #设置超管账户信息
    username: root  #超管账户名
    resetCode: ^&23#sEdkfdsSa  #重置密码时的重置码
  default:
    password: 123456 #新建用户时默认密码
    avatar: /static/avatar/dog.jpg #新建用户时默认头像

logging:
  config: classpath:logback-spring.xml

